default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: nearly
  password: <%= ENV["NEARLY_DATABASE_PASSWORD"] %>
  host: localhost
  database: nearly_development

test:
  <<: *default
  username: nearly
  password: <%= ENV["NEARLY_DATABASE_PASSWORD"] %>
  host: localhost
  database: nearly_test

production:
  <<: *default
  database: nearly_production
  username: nearly
  password: <%= ENV["NEARLY_DATABASE_PASSWORD"] %>